// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnY7DWNE23w4jCvTyMsm6-kQAhv2TYqUg',
    appId: '1:187636378820:web:f438eb503934a3f7052d91',
    messagingSenderId: '187636378820',
    projectId: 'quranproject-a74ac',
    authDomain: 'quranproject-a74ac.firebaseapp.com',
    storageBucket: 'quranproject-a74ac.appspot.com',
    measurementId: 'G-NJX31P6YPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWUws6umw3rhjfck2TXrbxNoaWr7Dtt5k',
    appId: '1:187636378820:android:6b904845e828e887052d91',
    messagingSenderId: '187636378820',
    projectId: 'quranproject-a74ac',
    storageBucket: 'quranproject-a74ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGDRtwhLAGUoJ4OKMTWpRbP5wexHt_Oo',
    appId: '1:187636378820:ios:7e148fc5b8730a2b052d91',
    messagingSenderId: '187636378820',
    projectId: 'quranproject-a74ac',
    storageBucket: 'quranproject-a74ac.appspot.com',
    iosBundleId: 'com.example.quraanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGDRtwhLAGUoJ4OKMTWpRbP5wexHt_Oo',
    appId: '1:187636378820:ios:1e2e82e4f72395df052d91',
    messagingSenderId: '187636378820',
    projectId: 'quranproject-a74ac',
    storageBucket: 'quranproject-a74ac.appspot.com',
    iosBundleId: 'com.example.quraanProject.RunnerTests',
  );
}
